In [24]:
import pandas as pd
import soccerdata as sd

# Initialize the MatchHistory object
mh = sd.MatchHistory(leagues=["ITA-Serie A", "ENG-Premier League", "ESP-La Liga", "FRA-Ligue 1", "GER-Bundesliga"],
                     seasons=["23", "22", "21", "20", "19", "18"])

hist = mh.read_games()
hist.reset_index(inplace=True)
hist.head()

[05/06/24 19:05:52] INFO     Saving cached data to C:\Users\jbuck\soccerdata\data\MatchHistory        ]8;id=514062;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=264896;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_common.py#92\92]8;;\

,league,season,game,date,home_team,away_team,FTHG,FTAG,FTR,HTHG,...,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,referee
0,ENG-Premier League,1819,2018-08-10 Man United-Leicester,2018-08-10 12:00:00,Man United,Leicester,2,1,H,1,...,2.03,1.85,1.79,17.0,-0.75,1.75,1.70,2.29,2.21,A Marriner
1,ENG-Premier League,1819,2018-08-11 Bournemouth-Cardiff,2018-08-11 12:00:00,Bournemouth,Cardiff,2,0,H,1,...,1.98,1.92,1.83,20.0,-0.75,2.20,2.13,1.80,1.75,K Friend
2,ENG-Premier League,1819,2018-08-11 Fulham-Crystal Palace,2018-08-11 12:00:00,Fulham,Crystal Palace,0,2,A,0,...,1.95,1.96,1.87,22.0,-0.25,2.18,2.11,1.81,1.77,M Dean
3,ENG-Premier League,1819,2018-08-11 Huddersfield-Chelsea,2018-08-11 12:00:00,Huddersfield,Chelsea,0,3,A,0,...,1.98,1.90,1.84,23.0,1.00,1.84,1.80,2.13,2.06,C Kavanagh
4,ENG-Premier League,1819,2018-08-11 Newcastle-Tottenham,2018-08-11 12:00:00,Newcastle,Tottenham,1,2,A,1,...,2.01,1.88,1.81,20.0,0.25,2.20,2.12,1.80,1.76,M Atkinson

In [26]:
import pandas as pd

# Assuming 'df' is your DataFrame loaded with the data

# List of columns you want to keep
columns_to_keep = ['league', 'season', 'game', 'date', 'home_team', 'away_team', 'B365H', 'B365D', 'B365A']

# Drop all other columns
hist = hist[columns_to_keep]
import pandas as pd

# Assuming 'df' is your DataFrame

# Convert 'date' to datetime if it's not already
hist['date'] = pd.to_datetime(hist['date'])

# Extract only the date part
hist['date'] = hist['date'].dt.date


# Now 'df' only contains the columns specified
hist

,league,season,game,date,home_team,away_team,B365H,B365D,B365A
0,ENG-Premier League,1819,2018-08-10 Man United-Leicester,2018-08-10,Man United,Leicester,1.57,3.9,7.50
1,ENG-Premier League,1819,2018-08-11 Bournemouth-Cardiff,2018-08-11,Bournemouth,Cardiff,1.90,3.6,4.50
2,ENG-Premier League,1819,2018-08-11 Fulham-Crystal Palace,2018-08-11,Fulham,Crystal Palace,2.50,3.4,3.00
3,ENG-Premier League,1819,2018-08-11 Huddersfield-Chelsea,2018-08-11,Huddersfield,Chelsea,6.50,4.0,1.61
4,ENG-Premier League,1819,2018-08-11 Newcastle-Tottenham,2018-08-11,Newcastle,Tottenham,3.90,3.5,2.04
...,...,...,...,...,...,...,...,...,...
10644,ITA-Serie A,2324,2024-05-05 Milan-Genoa,2024-05-05,Milan,Genoa,1.45,4.5,6.50
10645,ITA-Serie A,2324,2024-05-05 Roma-Juventus,2024-05-05,Roma,Juventus,2.88,3.1,2.70
10646,ITA-Serie A,2324,2024-05-05 Verona-Fiorentina,2024-05-05,Verona,Fiorentina,3.10,3.3,2.30
10647,ITA-Serie A,2324,2024-05-06 Salernitana-Atalanta,2024-05-06,Salernitana,Atalanta,7.50,5.5,1.36
10648,ITA-Serie A,2324,2024-05-06 Udinese-Napoli,2024-05-06,Udinese,Napoli,3.75,3.6,1.95

In [27]:
hist.to_csv('odds_data_for_model.csv', index=False)
# Cell 1: Check current branch
!git branch

# Cell 2: Add CSV file to Git
!git add odds_data_for_model.csv

# Cell 3: Commit changes
!git commit -m "Added corresponding CSV data"

# Cell 4: Push to GitHub (assuming the current branch is 'main')
!git push origin main

* main
[main 40c082a] Added corresponding CSV data
 1 file changed, 10650 insertions(+)
 create mode 100644 odds_data_for_model.csv

To https://github.com/Jbuck1016/Predicting-Matches
   7199fe6..40c082a  main -> main

In [28]:
!git add Loading_In_Odds_Data.ipynb

# Cell 3: Commit changes
!git commit -m "Added Jupyter notebook"

# Cell 4: Push to GitHub
!git push origin main

warning: in the working copy of 'Loading_In_Odds_Data.ipynb', LF will be replaced by CRLF the next time Git touches it

[main f24b674] Added Jupyter notebook
 1 file changed, 272 insertions(+)
 create mode 100644 Loading_In_Odds_Data.ipynb

To https://github.com/Jbuck1016/Predicting-Matches
   40c082a..f24b674  main -> main